### ISSUE TITLE
KafkaTopicRepositoryTest uses shared CircuitBreaker

### ISSUE THREAD

**Issue by mneverov** [zalando/nakadi#1037]
### Description
KafkaTopicRepositoryTest uses shared CircuitBreaker. HystrixKafkaCircuitBreaker gets circuit breaker from the HystrixCircuitBreakerFactory which gets it from the cache (static map)- see com.netflix.hystrix.HystrixCircuitBreaker.Factory#circuitBreakersByCommand.  
As the result tests in KafkaTopicRepositoryTest class depend on each other and on the order of tests execution. JUnit runs tests in default order which is by hashes of their names sorted in ascending order. 
Any test with a hash of the test name greater than `whenKafkaPublishTimeoutThenCircuitIsOpened` will inherit circuit breaker in `OPEN` state from it which may be unexpected.

### Proposals
- do nothing
- add explicit annotation `FixMethodOrder.DEFAULT` with a comment about shared CircuitBreaker
- refactor test to use mocked CircuitBreaker

**Comment by antban** [comment]
Hystrix support was removed in #1357, closing
