### ISSUE TITLE
Unicode characters are received corrupted if a default "application/json" content type is set

### ISSUE THREAD

**Issue by ovolynets** [zalando/nakadi#1065]
I am sending unicode characters such, as ⌀ or ½, as part of Nakadi events. The payload is sent with the default Content-Type header of `application/json`. The server, however, accepts charset of ISO-8859-1 as default, set by Spring, see https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/StringHttpMessageConverter.java#L63.
Conversion from UTF-8 to ISO-8859-1 corrupts unicode data. This part of the code is responsible for the default charset:
https://github.com/zalando/nakadi/blob/1643b2182c1b4bb257ad6d822f48971eeaf9f91f/src/main/java/org/zalando/nakadi/config/WebConfig.java#L71
With changing the default charset to UTF-8 unicode symbols in the payload would be supported by default and this is what I suggest to change

**Comment by v-stepanov** [comment]
@ovolynets I could not reproduce this problem. Can you please show your code/script that leads to this result?

**Comment by ovolynets** [comment]
Not an issue, see https://github.com/zalando/nakadi/pull/1066#issuecomment-502587302
