### ISSUE TITLE
Retention time is 2 days by default but it should be 4 days

### ISSUE THREAD

**Issue by max-neverov** [zalando/nakadi#1190]
According to [the documentation](https://nakadi.io/manual.html#definition_EventTypeOptions) default value for the `retention_time` is 345600000 ms (4 days).
When an event is created without `options.retention_time` [the event retention_time is 2 days](https://github.com/zalando/nakadi/blob/master/app/src/main/resources/application.yml#L52), and also [db migration](https://github.com/zalando/nakadi/blob/master/database/migration/R2016_08_22/aruha-312-set-default-retention-time-when-it-was-not-provided.sql#L2)

[faq](https://github.com/zalando/nakadi/blob/master/docs/_documentation/faq.md#how-do-i-define-how-long-will-events-be-persisted-for) should be probably also updated since the following is no longer true:
```
At the moment, retention can't be defined via the API per event type.
```

**Comment by antban** [comment]
@max-neverov I've added pr to fix the old documentation and removed obsolete faq answer.

FYI, the default values may (and usually are) overridden in custom deployments of the project, so it makes sense to contact your owner of nakadi deployment.
