### ISSUE TITLE
Event streaming with httpie is not working

### ISSUE THREAD

**Issue by bocytko** [zalando/nakadi#139]
I tried out Nakadi on staging env (nakadi-testing, nakadi-staging). I was able to create an event type, post events and see updated partition offsets. However, the event retrieval via Nakadi (`/event-types/{event-name}/events` is accepted with `HTTP/1.1 200 OK`, but afterwards it's stuck and times out on client side.

```sh
$ http -v -a mytok: --verify no https://nakadi-testing.aruha-test.example.org/event-types/order.ORDER_CANCELLED/events X-Nakadi-Cursors:"[{\"partition\": \"1\", \"offset\": \"0\"}]"
GET /event-types/order.ORDER_CANCELLED/events HTTP/1.1
[...]
X-Nakadi-Cursors: [{"partition": "1", "offset": "0"}]

HTTP/1.1 200 OK
[...]
X-Flow-Id: cVKWzOoUKzlnD0pzcJzvO4LO
```

I was able to reproduce this behavior also locally. I ran `./gradlew startDockerContainer` on nakadi-jvm (a67bf5d322991c6983fe7aa45a4daca4dbb74a48) to start Nakadi.

After checking the Kafka topics directly, I can confirm that the events have been written correctly to the topic and can be read from Kafka using `./kafka-console-consumer.sh --zookeeper localhost:2181 --topic order.ORDER_RECEIVED --from-beginning`.

**Comment by v-stepanov** [comment]
Hi @bocytko 
Thanks for feedback

Probably there's some problem with `http` utility you use.
I tried to read from your event-type with curl and it worked pretty fine for me  
```
curl -v -X GET \
-H "Authorization: Bearer ${TOKEN}" \
-H 'X-nakadi-cursors: [{"partition": "1", "offset": "0"}]' \
"https://nakadi-testing.aruha-test.example.org/event-types/order.ORDER_CANCELLED/events`
```
And the connection was open for me and I got 
```
{"cursor":{"partition":"1","offset":"1"},"events":[{"order_number": "123"}]}
```
And after that I got a an empty batch `{"cursor":{"partition":"1","offset":"1"}}` every 30 seconds.

Maybe `http` utility is not supposed to keep connection for so long? 

Also when you call this endpoint without parameters you get a batch-flush period set to 30 seconds. Maybe you should try a shorter one like batch_flush_timeout=3. Then you should get empty-batch message every 3 seconds.

Also, maybe `http` utility somehow caches the output till connection is closed (but it actually never closes if you don't specify some possible exit conditions parameters like `stream_limit` or `stream_timeout`)

**Comment by bocytko** [comment]
@v-stepanov thanks for your detailed response! `http` is in fact [httpie](https://github.com/jkbrzt/httpie).

For support of [streamed responses](https://github.com/jkbrzt/httpie#streamed-responses), the option `--stream ...` needs to be used :unamused: (facepalm).
