### ISSUE TITLE
Improve logging of errors of push-endpoint

### ISSUE THREAD

**Issue by v-stepanov** [zalando/nakadi#14]
We need to improve the logging of push-endpoint. Currently if error-response is created on connexion-level we don't have too much log data about that. We just have simple access log from gunicorn:

> [02/Nov/2015:13:03:10 +0000] "POST /topics/eventstore.article.16/events HTTP/1.1" 400 152 "-" "Java/1.8.0_05"

But in this case we need at least to see the request body.
First we need to check if it is possible to configure connexion to log request body in a case of creation of error-response.

**Comment by valgog** [comment]
Will close this, as we will not do any further development on the python version
