### ISSUE TITLE
Update `org.json` version

### ISSUE THREAD

**Issue by a1exsh** [zalando/nakadi#1562]
We are using a 5+ years old release.  For example, `JSONObject::isEmpty()` is not there yet.

**Comment by sriganth3** [comment]
@a1exsh, I would like to contribute. I'm new to open source contribution.

**Comment by a1exsh** [comment]
@sriganth3 thank you for your interest (and reminding me of this issue I myself filed some months ago ;)

This project, while technically FOSS, is unfortunately not something that is used outside of Zalando, to the best of my knowledge.
What is your personal interest to contribute?

**Comment by a1exsh** [comment]
Let's **not** do that, actually, because of issues like this one: https://github.com/stleary/JSON-java/pull/453#issuecomment-610819809
(I've tried first with the current latest version `20240205` and seen all tests in `StrictJsonParserTest` break: not sure these are that much useful)
