### ISSUE TITLE
Support event type json-schema definition as object

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/nakadi#166]
It is inconvenient to provide event schema definition as a string.
Suggestion is to support schema_object field of type object along side/instead of schema string field

Also there is yaml mentioned, but json expected
https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L1182

**Comment by jkliff** [comment]
Is the quoted line correct? There's no mention of yaml there.

**Comment by AlexanderYastrebov** [comment]
@jkliff Line number changed. Now it is https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L1171
Just CTRL+F for yaml on that page

**Comment by valgog** [comment]
@AlexanderYastrebov I am closing this issue now. Please reopen if you still consider that you need non-string schema definition possibility.

Also, I suppose that if YAML submission should be implemented, could you create a separate ticket for that?
