### ISSUE TITLE
is eid in metadata now required or not?

### ISSUE THREAD

**Issue by drummerwolli** [zalando/nakadi#192]
in https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L879 it says regarding the metadata/eid "Clients are allowed to generate this", which sounds to me like its not mandatory to create this by yourself as a producer.

in https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L922 though it says that eid is required.

which one is the correct interpretation?

**Comment by rcillo** [comment]
The correct interpretation is the later: it is required.

Our usage of Kafka provides the safest persistence guarantee available, which guarantees "at least once" delivery semantics.

> acks=all This means the leader will wait for the full set of in-sync replicas to acknowledge the record. This guarantees that the record will not be lost as long as at least one in-sync replica remains alive. This is the strongest available guarantee.

On the other hand it means that we could reply with error when it would be successfully published. That would happen in the very rare event of timeout during replicas acknowledgement. See page 81, for example http://www.slideshare.net/miguno/apache-kafka-08-basic-training-verisign

That said, it's really important to provide a way for consumers to handle duplicates. That is one of the reasons why it's important to provide an UUID.

Thanks for the feedback regarding the API. I'll be improving it to make it clearer.

**Comment by drummerwolli** [comment]
well, then this is probably related to: https://github.com/zalando/nakadi/issues/193

**Comment by rcillo** [comment]
Yes, I agree that it's related but I would not say that ordering is a different topic than uniqueness.

**Comment by rcillo** [comment]
Fixed in #195
