### ISSUE TITLE
Transaction identifier for resource events

### ISSUE THREAD

**Issue by unlaut** [zalando/nakadi#193]
To correctly detect out-of-order events, producers should provide a transaction number (like Oracle's SCN, Posgres' WAL position etc. Better term welcome.) that is strictly monotonously increasing for each data_key. Providing this information should be mandatory for each event reporting a modification of persisted state, i.e. for Data Change Events / Resource Events. (Note: clock times are insufficiently reliable for strict ordering.) Typical CDC solutions are able to provide this information.

**Comment by BGehrels** [comment]
sequence_number could be an idea, version_number another one. Or ordering_sequence_number. or just order_number.

**Comment by rcillo** [comment]
Is this a feature that Nakadi should provide or something that producers should provide?

I agree that a sequential counter is required for consumers to reorder messages.

Currently this is already possible. There's nothing preventing producers from defining such a field.

Do you think that this should be enforced by Nakadi somehow?

**Comment by BGehrels** [comment]
I do not think that DataChangeEvent and BusinessEvent should be part of Nakadis API Spec at all. But as long as it is, the order_sequence must be part of the DataChangeEvent, because otherwise, one can not make sens of it on the receiving side

**Comment by tmuehl** [comment]
In general is it the responsibility of a producer to send events in the correct order. The promise Nakadi makes is that it guarantees to send events to consumers in the same order as they come in.

The only scenarios I can imagine, where a sequence number makes sense, are:
* The order of messages is messed up during network transportation from the producer to Nakadi. This should never happen as long as you don't produce events (that should be order among each other) from multiple applications (what should be avoided).
* The producer is a distributed third party application that provides such a sequence number among several instances, like an distributed database application.

**Comment by BGehrels** [comment]
I experienced some liveness problems with this approach in the past: If a sender has to send 1.000 messages, and the first one fails to deliver (i.e. due to not fitting in a schema or throwing NPEs during serialization), it will not be able to send the 999 other ones without sacrifying the ordering, meaning it has to "stop the world" and wait for this one problem to be fixed. If this happens on friday after EOB, this may mean night shifts or 3 days of delayed data that stacks up at the senders system. Regardless of the guarentees the message bus provides, i tend not to rely on ordering in distributed messaging systems for the sake of resilience.

But, the core question remains: Should the DataChangeEvent be part of the nakadi API (i don't think so, since it resides in a conceptual layer above nakadi) and therefore: Is this the right place to discuss this issue?

@unlaut What do you think?

**Comment by dehora** [comment]
> The order of messages is messed up during network transportation from the producer to Nakadi. This should never happen as long as you don't produce events (that should be order among each other) from multiple applications (what should be avoided).

I'm coming to this late, sorry, but the discussion was very interesting.

@tmuehl I pretty much agree expect that it won't be a mess up, it's more like a fact of distributed systems :) There are scenarios where this could happen, eg where there is a cluster of Nakadi servers under a load balancer (which is likely to be a common configuration) and a multi-process/threaded producer (which won't be that unusual). Producers can mitigate this by waiting for responses from Nakadi until sending the next event, but that hurts throughput and could actually be tricky to achieve if the producer service is itself a cluster (as it'll require the cluster members to coordinate). Nakadi can't guarantee any order until data reaches its boundaries, but it does have a way to sequence events to allow end to end ordering by using the `parent_eids` field in the `metadata` object. I think end to end signalling of ordering through the data and not having to rely on cluster/network details can be a good way to address @unlaut's concerns.  

 I agree with @rcillo that Nakadi doesn't prevent sending monotonically increasing values, I guess the question is should Nakadi provide general support for indicating order. Which gets to @BGehrels point about the the data change and business event types. These do seem to live on a higher level than Nakadi (alternatively one could argue that Nakadi is opinionated).  But there probably is value in having a structured JSON object in the stream with common properties to support things that come up again and again in these kind of systems and allows an arbitrary payload (even binary if base64 was an option). For example some of the `metadata` object's fields that exist for business/data event types are useful in general, but these aren't available in the `undefined` type. Possibly there could be an `enveloped` type that producers could use and which consumer clients can rely on. Other higher level event types could build on that common structure  (the `undefined` event type still has its use as do business/data, so they not have to  go away).

**Comment by rcillo** [comment]
I'm closing this issue since it already possible for users to specify any properties they consider necessary.

Migrating to a standard `envelop` might be one of the directions we move in the future, but I see no reason for this issue to remai open even more time without action.
