### ISSUE TITLE
Not getting started

### ISSUE THREAD

**Issue by akauppi** [zalando/nakadi#218]
[Slides probably only for Zalando users](https://docs.google.com/presentation/d/1ubJV5_koQvjfsZdfJDTcngr6W-z6DLg2lLxgNNTrsT4/edit?pli=1#slide=id.g10081019ef_0_10) explains on page 11 that this should work:

```
$ gradle startDockerContainer
```

It doesn't, for me (OS X, gradle 2.12, docker v.1.11):
```
$ gradle startDockerContainer
:compileJava
Note: /Users/akauppi/Git/nakadi/src/main/java/de/zalando/aruha/nakadi/config/JsonConfig.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileGroovy UP-TO-DATE
:processResources
:classes
:jar
:findMainClass
:startScripts
:distTar
:distZip
:bootRepackage
:generateScmSourceJson UP-TO-DATE
:buildDockerImage
Building docker image with tag: aruha/nakadi:AUTOBUILD
Running command: docker build -t aruha/nakadi:AUTOBUILD .
:buildDockerImage FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/akauppi/Git/nakadi/build.gradle' line: 309

* What went wrong:
Execution failed for task ':buildDockerImage'.
> docker build failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.584 secs
```

This is from commit 713f9cab561eb86578cc23e30b0cff2e63153fd0 of `nakadi-jvm` branch.

**Comment by antban** [comment]
Have you tried just running 
`gradle build && docker build -t aruha/nakadi:AUTOBUILD .`
in nakadi directory?

**Comment by v-stepanov** [comment]
@akauppi 
From this log I don't see the actual reason of failure.
You can try what @antban suggested or you can also try to run using `--stacktrace` flag to see more detailed error message when building:
`gradle startDockerContainer --stacktrace`

**Comment by rcillo** [comment]
In my understanding, this has been addressed here https://github.com/zalando/nakadi/pull/232
