### ISSUE TITLE
Nakadi API: `additionalProperties: true/false` is not valid Swagger/OpenAPI syntax.

### ISSUE THREAD

**Issue by ePaul** [zalando/nakadi#222]
There are some slight differences between Swagger's (now OpenAPI's) model schema and JSON schema. One of them is that the `additionalProperties` key [allows only object values](https://github.com/swagger-api/swagger-codegen/issues/1318#issuecomment-146302879) (which mean schemas), not boolean `true` (which would be equivalent to an empty object) nor `false` (which is the default if the key is omitted).

This makes the Nakadi API in the current form unusable with Swagger Codegen (these are simply ignored).

**Comment by dehora** [comment]
@ePaul what's the best way to express open for extensions? I would have gone with

```yaml
"additionalProperties": {}
```

but there's a comment [here](https://github.com/swagger-api/swagger-codegen/issues/1318#issuecomment-146841035) that suggests that isn't accepted either, so I'm not sure.

**Comment by dehora** [comment]
@ePaul @rcillo there's a pr here to help with swagger tooling: https://github.com/zalando/nakadi/issues/290. The codegen result and appearance in the ui are linked from there.
