### ISSUE TITLE
README needs an update + details

### ISSUE THREAD

**Issue by LappleApple** [zalando/nakadi#226]
I showed this project to Adrian Cockcroft and his first question was, "how is this different from other, similar projects?" This needs to be explained so that we can minimize friction for potential users and commentators. Ping me for our README template -- it'll help you answer the essential questions about what details to include in the README. :)

**Comment by dehora** [comment]
@LappleApple there were some readme improvements recently. Could you take a quick look and say what still needs to done?

**Comment by rcillo** [comment]
I'm closing this issue since README has been improved several times since this issue was created.
