### ISSUE TITLE
Monitor if kafka has none-existing brokers as replicas 

### ISSUE THREAD

**Issue by v-stepanov** [zalando/nakadi#25]

**Comment by v-stepanov** [comment]
We should connect to zookeeper and and check if some replicas set to none-existing brokers

**Comment by drummerwolli** [comment]
lets do this in the kafka appliance itself, so everyone using buku can profit from this ;-) ... https://github.com/zalando/saiki-buku/issues/21

**Comment by v-stepanov** [comment]
@drummerwolli, exactly :)
@CyberDem0n is already implementing that in buku, I believe you will see a pull-request soon.

**Comment by drummerwolli** [comment]
it is here already: https://github.com/zalando/saiki-buku/pull/20
