### ISSUE TITLE
openjdk

### ISSUE THREAD

**Issue by DaKine23** [zalando/nakadi#252]
Dockerfiles should start with 

FROM registry.opensource.zalan.do/stups/openjdk:8u91-b14-1-22

**Comment by ePaul** [comment]
Could you add some details why this is better than the current `FROM registry.opensource.zalan.do/stups/openjdk:8u77-b03-1-20`?

**Comment by hjacobs** [comment]
@ePaul security fixes :smirk:

**Comment by DaKine23** [comment]
> @ePaul security fixes :smirk:

**Comment by ePaul** [comment]
Maybe I'm too idealistic here, but I wish that every issue has a description which tells why something is to be done, not just what is done. That was the reason for my "Could you add the details".

In this case, a possible text could be this one:

> The currently used base image `registry.opensource.zalan.do/stups/openjdk:8u77-b03-1-20` of this project's Docker definitions has several security issues (in both the Ubuntu base system and the OpenJDK). Those are fixed in newer versions of the image.
> 
> To fix this, the Dockerfiles should start with
> 
>     FROM registry.opensource.zalan.do/stups/openjdk:8u91-b14-1-22

I guess now it's clear by the comments, but in the future that could be put right into the base issue description (aka initial comment).
