### ISSUE TITLE
Prefer Java 8 Time API to Joda Time

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/nakadi#274]

**Comment by rcillo** [comment]
We are aware of this issue. Thanks for reporting.

**Comment by rcillo** [comment]
Create #355 to fix this issue. Using Java 8 was not enough since it allows for offsets with seconds, which is not specified in RFC 3339. So I added a regex to make it even more restrict and adhere to the RFC completely. If you could please take a look @AlexanderYastrebov 👍
