### ISSUE TITLE
Consider refactoring of exception hierarchy

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/nakadi#278]
1. Use unchecked exceptions
 `I will try not to step into this controversial discussion, but only add a couple of points: it is easier to work with RuntimeException hierarchy, it plays smoothly with Spring and Nakadi is not a library to force clients dealing with exceptions`

2. Decouple from ResponseStatus (See #277)

**Comment by rcillo** [comment]
I'm closing this issue since not all members of the development team agree with using unchecked exceptions.

As for the second item, we could start using it from now on, but hardly would spend time doing a huge refactoring.
