### ISSUE TITLE
Validate that `partition_key_fields` are actually defined in the schema

### ISSUE THREAD

**Issue by jhorstmann** [zalando/nakadi#298]
This would avoid typos in the event definition which would only be apparent later when publishing events.

**Comment by elgalu** [comment]
This was closed as fixed or won't fix?

**Comment by adyach** [comment]
it is fixed, we have implementation for that and it is even released on live, but it is under feature toggle.

**Comment by adyach** [comment]
https://github.com/zalando/nakadi/pull/378
