### ISSUE TITLE
Problem when creating event type with numbers following dots

### ISSUE THREAD

**Issue by rcillo** [zalando/nakadi#307]
When creating an event type "event.type.123abc" it fails. It's currently not allowed to have numbers after dots.

```
{
    "status": 422,
    "title": "Unprocessable Entity",
    "detail": "Field \"name\" format not allowed\n",
    "type": "http://httpstatus.es/422"
}
```

**Comment by shuaibiyy** [comment]
We just hit into this issue. Please fix 😿

**Comment by valgog** [comment]
@zalando/aruha is this fixed?

**Comment by lmontrieux** [comment]
@valgog no, it isn't. But now it has a ticket in our Jira: ARUHA-828

**Comment by SergKam** [comment]
But this is documented and expected behavior. 
> pattern: '[a-zA-Z][-0-9a-zA-Z_]*(\.[a-zA-Z][-0-9a-zA-Z_]*)*'

Why do we need to fix this? 
https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L2104

**Comment by lmontrieux** [comment]
Oh, that's correct. In this case, I will close this issue, since the behaviour is exactly what is expected. Thanks @SergKam .

**Comment by shuaibiyy** [comment]
Hmm.. I think the documentation can be greatly improved :)
