### ISSUE TITLE
Bug when deleting and recreating an event type with existing subscription

### ISSUE THREAD

**Issue by rcillo** [zalando/nakadi#372]
1. Create an event type A
2. Create a subscription for A
3. Delete event type A
4. Recreate event type A
5. Tries to stream from the existing subscription

No events will be delivered, silently.

**Comment by v-stepanov** [comment]
I think when ET A is removed - we should remove all subscriptions that are subscribed only to A.
If the subscription is subscribed not only to A - we should remove everything from that subscription about ET A.
Wdyt?

**Comment by rcillo** [comment]
I like the idea of never deleting anything for real. Maybe we could keep it around but disabled? I think it makes it easier to debug and answer user questions when we can trace things. Removing then makes this task harder.

I was even against deleting event types. For me this is a hack just because we do not provide schema evolution and should be removed once this is in place.

**Comment by antban** [comment]
In current implementation it breaks everything. Maybe a better approach is to have db constraint on this.

**Comment by adyach** [comment]
The idea when higher level entities know nothing about lower level entities is pretty good and I see subscription is higher level entity comparing to event type. We can check for event type when we open the stream.
