### ISSUE TITLE
Use plain JSON to represent schema

### ISSUE THREAD

**Issue by PetrGlad** [zalando/nakadi#379]
Only supported type of event schea is json-schema - it is reasonable to accept schema content as JSON instead of JSON serialized into string.
This still leaves backward compatible way to introduce non JSON descriptions in future for which plain string can be used. 
That is following structures should be allowed (and possibly preferred):

``` json
{
  "name": "order.ORDER_RECEIVED",
  "owning_application": "order-service",
  "category": "business",
  "partition_strategy": "random",
  "enrichment_strategies": ["metadata_enrichment"],
  "schema": {
    "type": "json_schema",
    "schema": { "properties": {"order_number": {"type": "string" } } }
  }
}
```

and

``` json
{
  "name": "undef",
  "owning_application": "jinteki",
  "category": "undefined",
  "partition_strategy": "random",
  "schema": {
    "type": "json_schema",
    "schema": { "additionalProperties": true }
  }
}
```

**Comment by PetrGlad** [comment]
Looks like duplicate of https://github.com/zalando/nakadi/issues/166
However I suggest to not use string at all until there's anecessity for it. Current API spec forces unnecessary complications without real need (YAGNI).

**Comment by rcillo** [comment]
This has already been discussed in https://github.com/zalando/nakadi/pull/275

**Comment by valgog** [comment]
@PetrGlad please reopen this issue if you still consider that schema should be stored not as a string.

**Comment by PetrGlad** [comment]
Yes, I do think that using string for schema is a mistake. One of those cases when something added just-in-case once complicates things later. I bet no other schema types will ever be used here :) Still having a schema-type tag would be enough to allow migration path in future.

The problem is that my annoyance alone is not enough to drive this change.
