### ISSUE TITLE
Have a way to get actual validation schema for given event type or enrichment strategy

### ISSUE THREAD

**Issue by PetrGlad** [zalando/nakadi#380]
Feature request. Have a way to get actual validation schema for given event type or enrichment strategy. The JSON schema generated in `org.zalando.nakadi.validation.EventValidation` can be returned on HTTP GET e.g. at `/event-types/{type-name}` in field "effective_schema".

**Comment by rcillo** [comment]
@PetrGlad I had actually spent sometime in this task https://github.com/zalando/nakadi/pull/228

It would be great if you were interested in taking it from now on. You could use the above mentioned PR as an implementation example.

**Comment by PetrGlad** [comment]
I'll have a look.

**Comment by valgog** [comment]
@PetrGlad You wanted to do something in this direction. Please reopen if you have want to add that functionality.
