### ISSUE TITLE
Examples should mention necessity to specify media type

### ISSUE THREAD

**Issue by mtesseract** [zalando/nakadi#388]
Dear Nakadi Team,

the curl example for e.g. creating an event type fails with 415 Unsupported Media Type.
Adding the header "Content-Type: application/json"  fixes this.
I guess this should be added to the documentation.

Thanks,
Moritz

**Comment by sakky11** [comment]
Just a suggestion to nakadi team,Can we add Content type as "application/json" by default ?? So that every time we don't need to specify that.

**Comment by valgog** [comment]
@zalando/aruha is this still an issue?

**Comment by lmontrieux** [comment]
@mtesseract @valgog this has been fixed a while ago, I am closing this issue.
