### ISSUE TITLE
Nakadi silently overrides metadata.flow_id

### ISSUE THREAD

**Issue by rcillo** [zalando/nakadi#391]
When publishing an event, if the header `X-Flow-Id` is not provided, then Nakadi will silently override this field with a randomly generated value.

I would expect Nakadi not to override it, if it was provided, since it's mentioned in the API that "No preexisting value might be changed".

> 1. Once the validation succeeded, the content of the Event is updated according to the
>        enrichment rules in the order the rules are defined in the `EventType`.  No preexisting
>        value might be changed (even if added by an enrichment rule). Violations on this will force
>        the immediate **rejection** of the Event. The invalid overwrite attempt will be included in
>        the item's `BatchItemResponse` object.

It should either reject such event (which doesn't make much sense) or keep it, if present.

**Comment by LappleApple** [comment]
@rcillo This bug has been around for a while. Can we add a "Help Wanted" label to it? cc @v-stepanov @valgog @antban
