### ISSUE TITLE
Field default_statistics: API description does not match the validation procedure

### ISSUE THREAD

**Issue by chridou** [zalando/nakadi#411]
When creating an event, according to the API specification there can be a field "default_statistics". When that field is provided, you will get the following error message:

The error response says, it should be "default_statistic"

`{"type":"http://httpstatus.es/400","title":"Bad Request","status":400,"detail":"Unrecognized field \"default_statistics\" (class org.zalando.nakadi.domain.EventType), not marked as ignorable (11 known properties: \"schema\", \"default_statistic\", \"partition_strategy\", \"name\", \"owning_application\", \"category\", \"write_scopes\", \"read_scopes\", \"enrichment_strategies\", \"partition_key_fields\", \"options\"])\n at [Source: java.io.PushbackInputStream@4c7c16dd; line: 1, column: 1053] (through reference chain: org.zalando.nakadi.domain.EventType[\"default_statistics\"])"}`

**Comment by rcillo** [comment]
We just changed the API.
