### ISSUE TITLE
Binary distributions not available

### ISSUE THREAD

**Issue by muller** [zalando/nakadi#439]
Hello,

I can't find a way to run nakadi without compiling the source. I have tried maven central, dockerhub, and github releases page but I can't find a way to run nakadi.

The only version of nakadi available in maven central is "org.zalando" % "nakadi" % "1.0.0".
There is no occurrence of nakadi on dockerhub.
The release page https://github.com/zalando/nakadi/releases only offer source distribution. 

Is there any way I can run nakadi with a simple command like `java -jar` / `docker run` / `docker-compose up` / `./nakadi-start.sh` ?

I also would like to embed it into my tests in a approach like https://github.com/chbatey/kafka-unit so I need to be able to add it to my mvn / gradle / sbt.

Regards,
Leo

**Comment by adyach** [comment]
@muller hi,
you can start Nakadi like described here locally https://github.com/zalando/nakadi#running-a-server

**Comment by PetrGlad** [comment]
A default docker image would be indeed welcome.

**Comment by muller** [comment]
@adyach, gradle to run it locally is excellent. Specially when you are developing nakadi.

If I am developing an application that uses nakadi I don't expect to clone the repo, what I expect is to just run it.

Like in https://github.com/yahoo/pulsar/blob/master/docs/GettingStarted.md#starting-a-standalone-pulsar-server

Cheers,

**Comment by dr4ke616** [comment]
Ive been having issues running Nakadi locally for some time now as well when using `./gradlew startNakadi`. It would be nice to have, at the very least, releases available on Docker Hub so there is no need for someone who is developing an application that uses Nakadi to compile Nakadi code.

**Comment by rcillo** [comment]
If someone feels like creating a PR with a gradle task for building and publishing such image, it would be very welcome.

We could add this gradle task to our build task, so every time we create a new version of Nakadi we would automatically publish it somewhere.

**Comment by PetrGlad** [comment]
Since Nakadi already has Dockerfile so autobuild (Travis?) missing parts are:  
1. Set project property `dockerImageVersion` to e.g. build counter or release version for release builds
2. Set project property `dockerImageVersion`  to `registry.opensource.zalan.do/aruha/nakadi`
3. After tests pass:
```
   ./gradlew buildDockerImage 
   ./gradlew pushDockerImage
```

**Comment by LappleApple** [comment]
Hi @PetrGlad @rcillo, are we good here, or do you prefer a "Help Wanted" label to encourage someone to create the gradle task-related PR mentioned above?

**Comment by LappleApple** [comment]
Trying again on my last question ...

**Comment by rcillo** [comment]
We follow the philosophy of running a single process per docker. We provide docker-compose to bind all dependencies together. It is a single command, just run `gradlew startNakadi`. We have no plans at supporting a docker image with all dependencies bundled.

**Comment by LappleApple** [comment]
+1 @rcillo, thanks for resolving
