### ISSUE TITLE
Dockerize Travis-CI builds

### ISSUE THREAD

**Issue by valgog** [zalando/nakadi#44]
According to https://docs.travis-ci.com/user/docker/ it is possible to `docker-compose` to build in travis-ci.

Currently we use Docker build of the ZooKeeper and Kafka, but still use the pip3 installer directly and not as a docker run. 

Actually experimenting with `docker-compose` could be even more interesting, and will make it possible to build all the components of the system the same way as we would in production.

**Comment by v-stepanov** [comment]
@valgog 
I don't completely understand this ticket.
We already have all docker-building stuff in a gradle file, so in travis we just make gradle to build and run docker containers (https://github.com/zalando/nakadi/blob/nakadi-jvm/.travis.yml)
So I don't see any advantage with using docker-compose.

**Comment by valgog** [comment]
This is an old ticket, that was created before we had it :-)

**Comment by valgog** [comment]
Ah, the idea was also to experiment with Docker compose...
