### ISSUE TITLE
Need an API exposing running version

### ISSUE THREAD

**Issue by avb1989** [zalando/nakadi#476]
It would be nice to have  an API exposing the version of the running Nakadi instance (since it might be maintained by one team and used by others). Something like a SHA id in version might be helpful to refer to the corresponding version of API schema that is deployed.

**Comment by adyach** [comment]
@avb1989 we have such endpoint, I think we just missed it in api. 
https://nakadi-url/version
{
  "scm_source": {
    "author": "vstepanov",
    "revision": "e68c983d64a4080a12dddb333363a21814e430f5",
    "status": "",
    "url": "git:https://github.com/zalando/nakadi.git"
  }
}

**Comment by avb1989** [comment]
Cool !
