### ISSUE TITLE
Introduce the option of specifying a dedicated topic for a set of event types

### ISSUE THREAD

**Issue by coders-kitchen** [zalando/nakadi#485]
At the moment Nakadi creates one topic per event type.

This is fine for a lot of use case, but it gives away the feature of Kafka to combine multiple events on a topic. And in this regards the order guarantees per partition.

For example a order system that uses events in the background would make use of it.
So an order is created before it can be be cancelled etc. pp. .

At the moment you have to work around by specifying a meta-schema that is open enough to cover all the possible event types.

**Comment by rcillo** [comment]
@coders-kitchen isn't it enough to specify 2 schemas and combine them using `anyOf`?

**Comment by lmontrieux** [comment]
@coders-kitchen do you have any additional input on this?

**Comment by lmontrieux** [comment]
@coders-kitchen I'm closing this because it has been inactive for a long time. Please feel free to re-open if you'd like us to explore this further. Thank you for taking the time to raise the issue!
