### ISSUE TITLE
Validation error when publishing a valid event-type

### ISSUE THREAD

**Issue by kanuku** [zalando/nakadi#513]
When publishing an event, nakadi returns a validation error. The event seems valid, this might be a bug in the validation lib you're using.
**environment:** `staging`
**event-type ends with:** `test-process-chain-logistics-clients_process_status_changed`

The schema:

```json
{
  "type":"object",
  "properties": {
    "process_instance": {
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "subject_meta_data": {
      "type": "object"
    }
  }
}
```

The event we try to publish:
```json
[
  {
    "metadata": {
      "eid": "422ad7c5-93d6-4093-9a9d-327cd8f9b362",
      "occurred_at": "2016-12-14T12:10:31Z"
    },
    "process_instance": "/test-process-chain-logistics-clients/4f3381b0-c1f6-11e6-bcd7-43aa39b531de",
    "subject": "/test-process-chain-logistics-clients/4f3381b0-c1f6-11e6-bcd7-43aa39b531de",
    "status": "/processes/status/process-chain-in-preparation",
    "subject_meta_data": {
      "is_root": "true"
    }
  }
]
```

The error:
```json
[
  {
    "publishing_status": "failed",
    "detail": "#/subject_meta_data: extraneous key [is_root] is not permitted",
    "step": "validating",
    "eid": "422ad7c5-93d6-4093-9a9d-327cd8f9b362"
  }
]
```

**Comment by rcillo** [comment]
@kanuku this is the expected behaviour. Please refer to the following documents for the reason why:

- https://docs.google.com/document/d/1FmGHxI9oklxN16LKZe1UG_U21jtQFVCtLtRiC2W1pAk/edit#heading=h.tvwrqalwl0nc
- https://docs.google.com/document/d/1FmGHxI9oklxN16LKZe1UG_U21jtQFVCtLtRiC2W1pAk/edit#heading=h.7hwuy21sl20

You can fix this by making your schema explicitly describe such `is_root` property. This is now supported:

```json
{
  "type":"object",
  "properties": {
    "process_instance": {
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "subject_meta_data": {
      "type": "object",
      "properties": {
        "is_root": {
          "type": "boolean"
        }
      }
    }
  }
}
```

If you do need to use loosely defined schema, which accept arbitrary objects, there is the possibility to create a `compatiblity_mode: false` event type. Please check https://github.com/zalando/nakadi/blob/2195cef34660b16f06be2ede2ac0ece6db9a16e0/api/nakadi-event-bus-api.yaml#L1598-L1599

Be aware that this feature is under validation on staging. The live rollout is not yet planned.

**Comment by kanuku** [comment]
@rcillo 
I cannot create an event-type with a loosely defined schema on nakadi using `compatiblity_mode: true/compatible` because it is not possible for nakadi to validate the schema, see example below:
```json
"schema": {
"type": "json_schema",
"schema": "{\"additionalProperties\": true}"
}
```

I do can create an event-type with a loosely defined schema on nakadi using `compatiblity_mode: true/compatible` even though nakadi will not allow me to create events that are valid according to the accepted schema below:
```json
{
  "type":"object",
  "properties": {
    "process_instance": {
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "subject_meta_data": {
      "type": "object"
    }
  }
}
````

Would it not make sense for nakadi to apply the same type of validation regarding the loosely defined schema's on both variants, during the creation of the event-type?

**Comment by valgog** [comment]
@kanuku I could not understand your request :(

Do you mean that `"type": "object"` is allowed?

I think the biggest complexity here is, that `additionalProperties` are defaulted to `true` for classical json-schema, and Nakadi in compatibility mode default it to `false`. 

In the example above, `subject_meta_data` field will be allowed by Nakadi, but the only value that it would be able to get, would be an empty object `{}` or `null`.

**Comment by rcillo** [comment]
@kanuku as @valgog mentioned, `subject_meta_data` definition accepts empty objects, e.g. `{}`. The way we envisioned it, users would further expand this definition by adding `properties` to it.

**Comment by rcillo** [comment]
Nakadi compatibility mode `forward` covers this use case.
