### ISSUE TITLE
Create an endpoint to list all consumers of particular event-type

### ISSUE THREAD

**Issue by synthorchid** [zalando/nakadi#547]
It would be very useful to know which applications are consuming an event-type.
The identifier for the application can be the application id in Yourturn.

**Motivation:** Sometimes it is necessary to notify event consumers about (potentially breaking) schema changes and it is hard to do when you don't know all consumers.

**Endpoint Proposal:** `GET /event-types/{event-type}/consumers`

**Comment by SergKam** [comment]
@synthorchid We have implemented this in Nakadi UI
Is this page covers all your needs? 
https://nakadi-ui-staging.aruha-test.zalan.do/#types/shop-updater.article.ad1?tab=ConsumerTab

**Comment by lmontrieux** [comment]
@synthorchid is the UI solution satisfactory? Can we close this issue?

**Comment by synthorchid** [comment]
@SergKam @lmontrieux  yes, this page is enough! I have created the issue before this feature was implemented.
