### ISSUE TITLE
Be able to set the cursors of a subscription to a manual offset

### ISSUE THREAD

**Issue by tmuehl** [zalando/nakadi#571]
We had outages of components in past which required to re-consume the last `X` events. The only chance to re-consume them, right now is to create a new subscription. This can be costly, depending on  the retention time.

Providing an easy way to set back cursors of a subscription on demand would be highly appreciated.

**Comment by tmuehl** [comment]
Being later able to do this via the UI would be Vanilla. :)

**Comment by SergKam** [comment]
I added this as a reminder for UI https://github.bus.zalan.do/aruha/nakadi-ui/issues/65

**Comment by tmuehl** [comment]
@SergKam Awesome, thanks!

**Comment by adyach** [comment]
#612

**Comment by adyach** [comment]
Implemented in #612

**Comment by v-stepanov** [comment]
"Vanilla" solution will be implemented within UI project soon :)
