### ISSUE TITLE
Support persistence for EventTypes

### ISSUE THREAD

**Issue by jkliff** [zalando/nakadi#62]
There are some possibilities for the persistence layer for the EventType data.
- postgres (+ good knowhow, rds, - more coding)
- mongo (+ already implemented the basics, adequate for json objects)
- direct key value store (aws?)
It is convenien to be able to read/write directin JSON, but probably all will support this.

**Comment by valgog** [comment]
If ZooKeeper value size limitation are not a problem, we already have a 'free' maintained instance for nakadi
