### ISSUE TITLE
`/subscriptions` POST is assigned a read scope 

### ISSUE THREAD

**Issue by dehora** [zalando/nakadi#646]
The [/subscriptions](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L822-L827) POST request has a scope of `nakadi.event_stream.read`. I'm not sure what the right scope is, but `nakadi.event_stream.read`  sounds incorrect.

**Comment by lmontrieux** [comment]
@dehora it does sound correct to me, as the only point of a subscription is to read an event stream. I suppose having a POST request with a read scope is a bit strange, but it is in fact the first step towards reading events.

**Comment by lmontrieux** [comment]
I'm closing this as 'invalid', feel free to re-open if you want to discuss it further.
