### ISSUE TITLE
 /subscriptions/{subscription_id}/cursors POST is assigned a read scope

### ISSUE THREAD

**Issue by dehora** [zalando/nakadi#647]
The [ /subscriptions/{subscription_id}/cursors](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L977) POST request has [a scope of `nakadi.event_stream.read`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1003-L1007). I'm not sure what the right scope is, but `nakadi.event_stream.read`  sounds incorrect.

**Comment by lmontrieux** [comment]
@dehora Posting cursors is a part of the consumption process, so it seems to me that `nakadi.event_stream.read` is correct. It looks a bit weird that a POST request requires a read scope, but I think it makes sense in this case.

**Comment by lmontrieux** [comment]
I'm closing this as 'invalid'. Feel free to re-open if you want to discuss it further
