### ISSUE TITLE
/subscriptions/{subscription_id}/cursors PATCH is assigned a read scope

### ISSUE THREAD

**Issue by dehora** [zalando/nakadi#648]
The [ /subscriptions/{subscription_id}/cursors](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L977) PATCH request has [a scope of `nakadi.event_stream.read`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1070-L1074). I'm not sure what the right scope is, but `nakadi.event_stream.read`  sounds incorrect.

**Comment by lmontrieux** [comment]
@dehora same remark as in issue #647

**Comment by lmontrieux** [comment]
I'm closing this as 'invalid'. Feel free to re-open if you want to discuss it further
