### ISSUE TITLE
API resources missing scopes

### ISSUE THREAD

**Issue by dehora** [zalando/nakadi#649]
Multiple API resources have no scopes documented. Ignoring `/metrics` which is documented as having no auth checks, there are at least sixteen resources without scopes - list below.

- [`/event-types GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L112)
- [`/event-types/{name} GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L198)
- [`/event-types/{name}/schemas GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L488)
- [`/event-types/{name}/schemas/{version} GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L534)
- [`/settings/blacklist GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1272) 
- [`/settings/blacklist/{blacklist_type}/{name} PUT`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1315)
- [`/settings/blacklist/{blacklist_type}/{name} DELETE`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1332)
- [`/settings/features GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1351)
- [`/settings/features POST`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1371)
- [`/storages GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1389)
- [`/storages POST`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1408)
- [`/storages/{id} GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1436)
- [`/storages/{id} DELETE`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1462)
- [`/event-types/{name}/timelines POST`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1492)
- [`/event-types/{name}/timelines GET`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1531)
- [`/event-types/{name}/timelines/{id} DELETE`](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L1585)

**Comment by lmontrieux** [comment]
Jira ticket 830

**Comment by SergKam** [comment]
This is no longer valid since the scopes are deprecated in favor of new authorization mechanism.
