### ISSUE TITLE
[jvm] NakadiKafkaConsumer.readEvent is not thread safe

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/nakadi#65]
Implementation could lead to data loss due to race near queue assignment
https://github.com/zalando/nakadi/blob/nakadi-jvm/src/main/java/de/zalando/aruha/nakadi/repository/kafka/NakadiKafkaConsumer.java#L69

In general internal state should not be changed/changed+checked without proper synchronization

**Comment by v-stepanov** [comment]
Hi @AlexanderYastrebov 
It is not really supposed to be thread-safe. To read from kafka it uses kafka-client class KafkaConsumer which is not thread-safe, so NakadiKafkaConsumer has no chance to be thread-safe :)
But it really makes sense to mark it as not thread-safe in its JavaDoc. In a branch I currently work I already did that:
https://github.com/zalando/nakadi/blob/hila-streaming-preparations/src/main/java/de/zalando/aruha/nakadi/repository/kafka/NakadiKafkaConsumer.java#L24

**Comment by AlexanderYastrebov** [comment]
Okay. Looks like I looked to the wrong docs and assumed that KafkaConsumer is thread safe. I will close this as non relevant then.

**Comment by v-stepanov** [comment]
@AlexanderYastrebov 
KafkaConsumer was thread safe in kafka 0.8. 
In 0.9 it became not thread-safe :) 
They actually changed quite a lot in 0.9
