### ISSUE TITLE
/event-types/{name}/cursors-lag requires scope nakadi.event_type.write

### ISSUE THREAD

**Issue by GJL** [zalando/nakadi#652]
Getting the cursors lag through the low level API, requires the oauth scope ` nakadi.event_type.write`. However, according to the API documentation `nakadi.event_stream.read` is required (see https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L601)

**Comment by lmontrieux** [comment]
Fixed in #663
