### ISSUE TITLE
/event-types/{name}/shifted-cursors requires scope nakadi.event_type.write

### ISSUE THREAD

**Issue by dehora** [zalando/nakadi#662]
The spec defines a read scope [here](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L758-L765)

But the server requires the oauth scope `nakadi.event_type.write`.

```
{
  "error": "insufficient_scope",
  "error_description": "Insufficient scope for this resource",
  "scope": "nakadi.event_type.write"
}
```

See also https://github.com/zalando/nakadi/issues/652. Perhaps this has something to do with using `POST` instead of `GET` with a body. If so, `/event-types/{name}/cursor-distance` might be affected.

**Comment by lmontrieux** [comment]
Fixed in #663
