### ISSUE TITLE
send back absolute links rather than relative links in /subscriptions

### ISSUE THREAD

**Issue by HungUnicorn** [zalando/nakadi#682]
When iterating pages in /subscriptions, the next link returned is relative rather than absolute.

 e.g. subscription: 
next link in this case is  
`/subscriptions?owning_application=YOUR_APP&offset=20&limit=20`
but not 
`https://nakadi-live.aruha.zalan.do/subscriptions?owning_application=YOUR_APP&offset=20&limit=20`

Would it be better to return absolute link?

**Comment by lmontrieux** [comment]
@HungUnicorn @dehora I see from other discussions that you'd like absolute links to simplify clients. It is not the only place where we use server-relative URLs, so I think that if we are to go ahead with this, we should do it for all URLs we return. We'll discuss this internally during our alignment meeting on Monday.

**Comment by lmontrieux** [comment]
Created a ticket AURHA-871 for this. Thanks @HungUnicorn for reporting, we'll get back to you asap.

**Comment by lmontrieux** [comment]
@HungUnicorn @dehora thank you again for raising this issue. We discussed this in the team earlier this week, and agreed that this would be a good thing to implement.
Unfortunately, this does not quite square with our current priorities, and I can't commit to a time when we will get around to it. I'm going to tag this issue with 'help needed', as PRs are of course more than welcome.
