### ISSUE TITLE
Broken link to swagger file in documentation

### ISSUE THREAD

**Issue by lmontrieux** [zalando/nakadi#749]
The link to the swagger file is broken in the last line of this section: https://zalando.github.io/nakadi/manual.html#subscriptions
(right before the "creating subscriptions" heading)

this issue was initially reported on nakadi-manual: https://github.com/zalando-nakadi/nakadi-manual/issues/63

**Comment by SergKam** [comment]
Also the link is broken in:
 More detailed information can be found in the `manual`.

**Comment by SergKam** [comment]
And in the client list, the links are not clickable.

**Comment by SergKam** [comment]
Fixed in #753
