### ISSUE TITLE
Add Nakadi Client Library for Haskell to the Manual

### ISSUE THREAD

**Issue by mtesseract** [zalando/nakadi#751]
Extend the list of clients contained in the manual by mentioning nakadi-client for Haskell.

**Comment by lmontrieux** [comment]
Thank you @mtesseract for your contribution. It's nice to see nakadi clients in a variety of languages!

**Comment by mtesseract** [comment]
Thank you!

**Comment by lmontrieux** [comment]
Fixed in #752
