### ISSUE TITLE
Support group based authorization for events

### ISSUE THREAD

**Issue by jhorstmann** [zalando/nakadi#767]
**As** the owner of an event type
**I want to** grant read access to groups of people
**So that** I don't have to manage access for individual people
**And** can use zack for managing access to events

**Comment by adyach** [comment]
@jhorstmann thank you for the proposal, in short there were such plans. we scheduled it for offline discussion and prioritisation.

**Comment by sp-niemand** [comment]
Plus one to that. Setting access on the team level would be preferable to setting it on the employee level.

**Comment by Grillkohle** [comment]
👍  as well. Small addition:
> I want to grant read access to groups of people
I'd prefer to be able to grant any kind of access to groups of people, be it read/write/admin.

**Comment by ePaul** [comment]
Just for understanding, would this be part of the public Nakadi code or Zalando's private authorization plugin?

**Comment by KonMann** [comment]
Since this is the most upvoted and subscribed to issue: Is there any news on this?

**Comment by lmontrieux** [comment]
I'm closing this issue because this is a Zalando-internal discussion. Any implementation would go into the authorization plugin, which is not part of the open source code for Nakadi.
