### ISSUE TITLE
Broken URL to Peek client

### ISSUE THREAD

**Issue by amrhassan** [zalando/nakadi#776]
I noticed that the URL for the `Peek` client on the "Clients" section of the documentation website. It might have moved to this URL https://github.com/kabdelrahman/peek.

**Comment by lmontrieux** [comment]
Nice catch, we'll get it fixed asap :)

**Comment by lmontrieux** [comment]
But if you want to send a PR, don't hesitate either :-D

**Comment by amrhassan** [comment]
I would have created a PR if I was sure what to do :).

It seems that the old project was deleted actually and the new one was created from a source dump of the old project (in one commit). It doesn't seem to be actively developed. Should the URL be changed to this other repo or should it be dropped completely?

**Comment by lmontrieux** [comment]
Fixed in #782
