### ISSUE TITLE
Question: Nakadi for people besides Zalando

### ISSUE THREAD

**Issue by eicnix** [zalando/nakadi#793]
Nakadi looks like a very nice tool for data integration between microservices but seems to be very Zalando specific. 

Are you interested in contributions that would extend Nakadi into a more general platform which wouldn't exclusivle target Zalando?

**Comment by adyach** [comment]
@eicnix good day, we give a lot of attention and effort that Nakadi could be used outside of Zalando (e.g. Nakadi plugins, which move vendor specific logic to internal repos). I am sure that with little a effort you can run Nakadi, taking into account, you are able to manage dependencies (Kafka, Zookeeper, Postrgres). Could you, please, elaborate on what is necessary to extend for you in order to be able to use it?

And of course, we are more than happy to accept external contributions!
Thank you for your interest in Nakadi.

**Comment by eicnix** [comment]
Hi @adyach, Thanks for your quick response.

Can you tell me more about the plugins? I didn't find much information about them in the documentation. 

Featurewise I am missing the export of the metrics in the Prometheus format. I would also add this myself.

Furthermore I am thinking about adopting OpenTracing as a way to track flows through the service landscape. Nakadi seems to use FlowIds, eid and parent_eids to achieve something similar. Are there any plans to support OpenTracing as an alternative?

**Comment by hjacobs** [comment]
@eicnix regarding OpenTracing: we are looking at OpenTracing in Zalando and doing PoCs --- Nakadi would obviously be in scope for this, too.

**Comment by adyach** [comment]
@eicnix Nakadi plugins are jars, which are put into classpath during build process, replacing the default implementation.
https://github.com/zalando/nakadi/blob/11ab7742a46c3958cdfc66db1a7452ce784b4ccb/src/main/resources/application.yml#L81
https://github.com/zalando-nakadi/nakadi-plugin-api

**Comment by eicnix** [comment]
@adyach Is there a builtin way to manage the access to specific event types based on scopes on the access token? As far as I can see there is only the possibility to manage the general access event type in the application config based on scopes. 
Do I write my own AuthorizationService for this?

**Comment by adyach** [comment]
@eicnix we use a little bit different schema for checking permission for event type, we do not have basic implementation, which uses scopes to verify event type access. in that case, you should implement your own `AuthorizationService`, you are right. Let me know, if you need any help with that.

**Comment by lmontrieux** [comment]
@eicnix @adyach It seems that this question has been answered, so I will be closing this issue now. Feel free to re-open if you would like to discuss this further.
