### ISSUE TITLE
We should not hard-code IPs of kafka brokers

### ISSUE THREAD

**Issue by v-stepanov** [zalando/nakadi#8]
Currently the kafka brokers are specified with IP addresses. And if with time all kafka brokers are recreated with different IPs - we will have problems.

**Comment by valgog** [comment]
Do we have some specific IPs in the repository?

**Comment by v-stepanov** [comment]
@valgog no, not here.

**Comment by v-stepanov** [comment]
For now I think the best way to do it is to specify the domain name of zookeeper elb in configuration of nakadi. And to ask it for a list of kafka brokers.
