### ISSUE TITLE
Incorrect spelling in "ocurred_at" field

### ISSUE THREAD

**Issue by themicha1** [zalando/nakadi#80]
Correct spelling is "occurred_at" (double c, double r). Please see: http://www.merriam-webster.com/dictionary/occur

https://github.com/zalando/nakadi/blob/nakadi-api-review-event-examples/api/nakadi-event-bus-api.yaml#L785

**Comment by bocytko** [comment]
@themicha1 this error has been fixed with 6fc80f6d9095d1ec61e2a9e9648c5591a5563a2d, see https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L762
