### ISSUE TITLE
Question: Service Communication

### ISSUE THREAD

**Issue by cheveyo20** [zalando/nakadi#810]
Hi,
i got a question concerning the direct interaction between services, how is this achieved with the Nakadi Eventing.
e.g.:
                                                                   
Business Event -> Service A -> Service B -> Decision if Service C or D is next based on a Flag -> Continue with C or D

This would be the processing Workflow:

Option 1) 
 - Service A produces START_EVENT
 - Service B consumes START_EVENT and generates START_PROCESSING_EVENT
 - Decision Services consumes START_PROCESSING_EVENT and fire either FLAG_C_IS_ENABLED or FLAG_D_IS_ENABLED
 and so on

Option 2)
 Zalando uses Apache Flink for CEP and SEP is this used for processing every event or just for monitioring/analytics? And generating the event for the next step, so not only a monitoring/ analysing solution its also possible to change business/dataflow logic here

 - Service A produces START_EVENT
 - Apache Flink detects pattern START_EVENT and fires START_EVENT_SERVICE_B
 - Service B consumes START_EVENT_SERVICE_B and generates START_PROCESSING_EVENT
 - Apache Flink detects pattern START_PROCESSING_EVENT and matches FLAG inside event payload
   and fires FLAG_C_IS_ENABLED or FLAG_D_IS_ENABLED

The Second approach is more like a event -> analyse -> command pattern. But with option 1 i have the problem that i cant change the workflow dynamically without touching maybe multiple services. The second approach gives me this possibility.

What do you think? I want to decouple but also control the dataflow i a very complex way like aggregation, joining and so on...

**Comment by lmontrieux** [comment]
I guess you could use several event types:

Service A produces START_EVENT to event type ET1
Service B consumes START_EVENT from event type ET1, and produces START_PROCESSING_EVENT to event type ET2
Decision service consumes START_PROCESSING_EVENT from event type ET2. If the decision is service C, then it produces an event to event type ET3_C. If the decision is service D, then it produces an event to event type ET3_D.
Service C consumes from event type ET3_C
Service D consumes from event type ET3_D

If later, you want to change your decision workflow, you only need to modify Decision Service. You can also add new types of decision, say events that need to be processed by Service E, by creating a new event type and updating your decision service.

Does this answer your question?

**Comment by cheveyo20** [comment]
Thanks :)
It partly answers my question, my goal is not only decouple services from each other, i also want to change workflow or actions.

For example your Services A & B:
If i would like to change the dataflow behaviour in the way that not every event is processed by B, so i would like to filter stuff. So theoretically i could touch Service A or B to behave in this way, but if i want to controll this more central and maybe in more complex scenarios would the option 2 with apache flink a good solution? Or are there other possibilities?

**Comment by cheveyo20** [comment]
Let me reformulate my question :) I am using a concrete example.

For example we are at zalando and a german customer does via the web backend the event "ORDER_RECIEVED":

So this event is consumed by Service A (is preparing a paper written bill) and Service B (is responsible for reserving the product). Ok this works for now :) The Event is somehow the command for Service A and B...

So now something has change in the logistic or what ever and german customers are now treated differently than from other countries. Therefore we write Service C which deals with this special case.
Service C now propably also listens to the ORDER_RECIEVED Event. 
Now we have the issue, if a german customer orders, the order is also processed via Service A, B, C.
Theoretically do solve it, i would need to reprogramm Service A and B and so on... 
How to solve this smart?

**Comment by lmontrieux** [comment]
Oh, I think I see what you want to do.

A solution would be to send all events to event type ORDER_RECEIVED. You then have a dispatcher service consuming from ORDER_RECEIVED, and forwarding events to other event types, depending on which of Service A, B, or C, should consume it. For example, if an event needs to be processed by Service A, your dispatcher will publish the event to the event type ORDER_RECEIVED_A, for which Service A is the only consumer.

If you need to make changes to your dataflow, you only need to update your dispatcher. Would this work for you?

**Comment by cheveyo20** [comment]
Yep so it would be like a Event Ingestion Bus -> EventProcessing -> CommandBus
Did you or some on tried this? Does it scale well? Are there any downsides?

**Comment by lmontrieux** [comment]
I haven't tried this personally but I understand that this is a common pattern. For scaling, you may want to think carefully about the number of partitions you want, especially in the initial event type, which will receive everything. I would tend to over-provision the number of partitions, especially if ordering is not a concern.

**Comment by lmontrieux** [comment]
I am closing this because I think the question was answered. If you think this requires more attention, please do not hesitate to re-open. Thank you very much for reaching out!
