### ISSUE TITLE
Nakadi and IAM Sandbox

### ISSUE THREAD

**Issue by fragsalat** [zalando/nakadi#826]
**Problem:**
Nakadi can not be used from a Kubernetes test cluster.

**Reason:**
The tokens on the test clusters  are issued using the IAM Sandbox environment. This makes the issued token invalid for IAM live environment and there makes Nakadi unusable for test clusters.

Example token body:
```json
{"sub":"credprov-purchase-orders-frontend-gateway-credentials-nakadi-token","https://identity.zalando.com/realm":"services","https://identity.zalando.com/token":"Bearer","azp":"credprov-purchase-orders-frontend-gateway-credentials-nakadi-token","https://identity.zalando.com/bp":"some-hash","iss":"https://sandbox.identity.zalando.com","exp":1516193015,"iat":1516189405,"https://identity.zalando.com/privileges":["com.zalando::nakadi.event_stream.read"]}
```

Error message:
```
'nakadi.AuthorizationException: token_assumed_unauthorized; Inferred from invalid response there was an auth issue, see https://github.com/zalando/nakadi/issues/645 raw_response={\"error\":\"invalid_token\",\"error_description\":\"Access Token not valid\"} (401)\n","stream":"stderr","time":"2018-01-17T12:26:48.425280423Z"}'
```

**Comment by ePaul** [comment]
I see two possible approaches here:

* somehow let Nakadi Staging accept both production tokens (for test services in Stups or datacenter) and sandbox tokens (for test services in Kubernetes), or

* have a separate "Nakadi Sandbox" (or similar) which accepts just sandbox tokens. This would not be accessible by Stups or datacenter services.

The second option is likely easier to implement, but will give less possibilities for interoperability testing (between Kubernetes and Stups/datacenter services).

**Comment by lmontrieux** [comment]
Thank you @fragsalat and @ePaul for reporting this issue. As it is related to the nakadi service we operate at Zalando, as opposed to the open source software that we develop on this repository, I have moved this issue to our internal ticketing system (Zalandos: look for ARUHA-1483). I am closing this issue so the discussion can be grouped where it most makes sense.
