### ISSUE TITLE
No raw (unformatted) view for the effective schema

### ISSUE THREAD

**Issue by Unisay** [zalando/nakadi#845]
**Actual behavior:**
I can only toggle event schema in the formatted view.
Switching off formatting, locks me into seeing only custom part of the schema.

![effective schema](https://user-images.githubusercontent.com/1009751/36313054-b8dc51b4-1330-11e8-935f-f001ec86e7af.gif)

**Expected behavior:**
I can toggle effective schema also in the raw (unformatted) view.

I need this in order to be able to copy effective schema from Nakadi UI. 
Copying it from formatted view produces invalid JSON (not well formed around multi-line text strings)

**Comment by lmontrieux** [comment]
Thank you for reporting this, @Unisay . Unfortunately Nakadi UI is not (yet) open source. This project is for the open source Nakadi project only, so I will have to close this issue. Would you mind reporting it internally instead?
