### ISSUE TITLE
Feature request: view effective schema without submitting event schema

### ISSUE THREAD

**Issue by Unisay** [zalando/nakadi#846]
I'd like to be able to see how would effective schema look like for the custom schema prior to (without) its submission.
This is convenient if I want to run schema validations during test phase, before deploying new event schema, say as a build step in CDP.
This way I could copy effective schema into the resource file in my repo, submit a PR that will go through schema validation tests and subsequently deploy my new event schema if tests are ok.

**Comment by lmontrieux** [comment]
Thank you for your PR, @Unisay . Unfortunately Nakadi UI is not (yet) open source. This project is for the open source Nakadi project only, so I will have to close this issue. Would you mind reporting it internally instead?
