### ISSUE TITLE
Provide a public Docker/docker-compose image for Nakadi

### ISSUE THREAD

**Issue by mdedetrich** [zalando/nakadi#878]
Although Nakadi provides a `Dockerfile` of the Nakadi service, the resulting Docker image isn't uploaded to any service (i.e. [Dockerhub](https://hub.docker.com/) or otherwise). Likewise an easily usable `docker-compose.yaml` file also isn't available so one can easily just run Nakadi with all of its service dependencies.

The use case for this is for integration testing/CI for clients written in Nakadi (in my case, https://github.com/zalando-incubator/kanadi). I want to easily be able to just start a Nakadi service locally using something like https://docs.travis-ci.com/user/docker/ so I can test my client against Nakadi (without needing to setup gradle or something along those lines)

**Comment by SergKam** [comment]
Please take a look to "semi-official" docker image and docker compose https://github.com/adyach/nakadi-docker.
Also there is a Nakadi UI docker-compose that creates the whole nakadi system including ui https://github.com/zalando-incubator/nakadi-ui#quick-start

**Comment by mdedetrich** [comment]
Yeah we are using this and it works, should I close the ticket?
