### ISSUE TITLE
Provided docker-compose is incompatible with OSX/Windows

### ISSUE THREAD

**Issue by marcos-diaz** [zalando/nakadi#902]
...Since `network_mode: "host"` is a Linux-only feature. (https://docs.docker.com/network/host/)

Why would you want to run it in MacOS or Windows? Local development / testing

Potential fix? Just remove `network_mode` setting and use implicit port/expose mapping, with internal service naming instead of localhost, aka proper Docker network routing.

**Comment by adyach** [comment]
we have [one](https://github.com/zalando/nakadi/issues/878) and [two](https://github.com/zalando/nakadi/issues/413) tickets for that already and even [pr](https://github.com/zalando/nakadi/pull/879) trying to fix it, any help on it is very appreciated

**Comment by lmontrieux** [comment]
Fixed in #980
