### ISSUE TITLE
Complex data models in Nakadi?

### ISSUE THREAD

**Issue by kisg** [zalando/nakadi#971]
I read a few blog posts about handling complex data models in Kafka from Zalando:

https://jobs.zalando.com/tech/blog/simplicity-by-distributing-complexity/
https://jobs.zalando.com/tech/blog/many-to-many-using-kafka/

Does Nakadi support such complex data modeling (and validating such schemas)? If not, do you have plans to support this in the future or do you recommend a different route for system design?

**Comment by adyach** [comment]
@kisg thank you for contributing!

Nakadi supports JSON schema for events, if you have not checked it out yet, here is more info https://nakadi.io/manual.html#using_event-types. Let me know if it is what you were asking for, or please, clarify more on your question.
