### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by MahshidZ** [zalando/nakadi#990]
Not sure why https://github.com/zalando/nakadi/issues/749 is closed. Link to swagger file in documentation is still broken. 

# Reason

The documentation uses a relative link. The relative addressing causes broken link in both Github documentation page and the Nakadi.io documentation page. 

## How relative linking is supported in Github markup files

Github appends the relative link to the following text: `https://github.com/user/repo/blob/branch/`

So the following code:

`[swagger](api/nakadi-event-bus-api.yaml)`

Will be translated to:

`[swagger](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml)`

Which actually does not exist! 

### Fix for Github

If you want to still keep the relative linking for Github, you can use the following address:

`[swagger](docs/_data/nakadi-event-bus-api.yaml)`

Please note that this fix works only on Github, and will break in Nakadi.io site. The next section explains the reason.

## How relative linking is supported in Nakadi.io domain 

The following text will be appended to the relative linking:` https://nakadi.io/`

So the following code:

`[swagger](api/nakadi-event-bus-api.yaml)`

Will be translated to:

`[swagger](https://nakadi.io/api/nakadi-event-bus-api.yaml)
`

Which actually does not exist! 

# Fix
By removing the relative linking and providing the full path, the link will be fixed in both places. So my suggested fix will be:

`[swagger](https://github.com/zalando/nakadi/blob/master/docs/_data/nakadi-event-bus-api.yaml)`

**Comment by lmontrieux** [comment]
Hi @MahshidZ ,

Thank you for reporting this issue. Would you like to open a pull request to fix this?

**Comment by MahshidZ** [comment]
Sure, I will do so.

**Comment by MahshidZ** [comment]
> Hi @MahshidZ ,
> 
> Thank you for reporting this issue. Would you like to open a pull request to fix this?

Sure, I will do so.
